version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    environment:
      - MONGO_URI=mongodb://mongo:27017/tracking_app
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
